# Generated by Django 2.2.6 on 2019-11-15 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_availablefacility_questionlist_questionsdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='availablefacility',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='availablefacility',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='availablefacility',
            name='education_type',
            field=models.IntegerField(blank=True, choices=[(1, 'School'), (2, 'College'), (3, 'Kinder Garden'), (4, 'Driving School')], null=True),
        ),
        migrations.AddField(
            model_name='availablefacility',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='availablefacility',
            name='financial_type',
            field=models.IntegerField(blank=True, choices=[(1, 'bank'), (2, 'atm'), (3, 'bureau_de_change')], null=True),
        ),
        migrations.AddField(
            model_name='availablefacility',
            name='health_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Hospital'), (2, 'Veterinary'), (3, 'Clinic'), (4, 'Dentist'), (5, 'Pharmacy'), (6, 'Health Post'), (7, 'Social Facility'), (8, 'Doctors')], null=True),
        ),
        migrations.AddField(
            model_name='availablefacility',
            name='opening_hours',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='availablefacility',
            name='website',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='availablefacility',
            name='type',
            field=models.IntegerField(choices=[(1, 'Health Facility'), (2, 'Education Facility'), (3, 'Security Force'), (4, 'Place Of Worship'), (5, 'Financial Institution')], default=0),
        ),
    ]
