# Generated by Django 2.2.6 on 2019-11-15 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20191115_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionsdata',
            name='open_space',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_data', to='core.OpenSpace'),
        ),
    ]
