# Generated by Django 2.2.7 on 2019-11-19 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20191119_0521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('replied', 'REPLIED')], max_length=15),
        ),
        migrations.AlterField(
            model_name='report',
            name='urgency',
            field=models.CharField(choices=[('high', 'HIGH'), ('medium', 'MEDIUM'), ('low', 'LOW')], max_length=15),
        ),
    ]
