# Generated by Django 2.2.6 on 2019-11-05 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20191104_0606'),
    ]

    operations = [
        migrations.CreateModel(
            name='NearbyAmenities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('open_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='core.OpenSpace')),
            ],
        ),
        migrations.CreateModel(
            name='HealthFacility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amenity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_facility', to='core.NearbyAmenities')),
            ],
        ),
        migrations.CreateModel(
            name='EducationFacility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amenity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_facility', to='core.NearbyAmenities')),
            ],
        ),
    ]
