# Generated by Django 2.2.7 on 2019-11-19 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20191119_0540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='date',
        ),
        migrations.RemoveField(
            model_name='report',
            name='image',
        ),
        migrations.RemoveField(
            model_name='report',
            name='location',
        ),
        migrations.RemoveField(
            model_name='report',
            name='message',
        ),
        migrations.RemoveField(
            model_name='report',
            name='name',
        ),
        migrations.RemoveField(
            model_name='report',
            name='open_space',
        ),
        migrations.RemoveField(
            model_name='report',
            name='reported_by',
        ),
    ]
