# Generated by Django 2.2.7 on 2019-11-19 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20191119_0542'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
