# Generated by Django 2.2.6 on 2019-11-07 09:35

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_resource_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openspace',
            name='polygon',
        ),
        migrations.AddField(
            model_name='openspace',
            name='polygons',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326),
        ),
    ]
