# Generated by Django 2.2.7 on 2019-11-19 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_report_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
