# Generated by Django 2.2.7 on 2019-11-19 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_report_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
