# Generated by Django 2.2.7 on 2019-11-19 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_report_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='urgency',
            field=models.CharField(choices=[('high', 'HIGH'), ('medium', 'MEDIUM'), ('low', 'LOW')], default='high', max_length=15),
        ),
    ]
