# Generated by Django 2.2.7 on 2019-11-19 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_report_urgency'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('replied', 'REPLIED')], default='pending', max_length=15),
        ),
    ]
