# Generated by Django 2.2.7 on 2019-11-19 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20191119_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='service'),
        ),
        migrations.AddField(
            model_name='suggesteduse',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='suggest'),
        ),
    ]
