# Generated by Django 2.2.7 on 2019-11-21 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20191121_0449'),
    ]

    operations = [
        migrations.AddField(
            model_name='availablefacility',
            name='phone_number',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
