# Generated by Django 2.2.7 on 2019-11-21 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_availablefacility_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='availablefacility',
            name='bank_network',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='availablefacility',
            name='bank_type',
            field=models.CharField(blank=True, choices=[('development', 'Development'), ('commercial', 'Commercial'), ('finance companies', 'Finance Companies'), ('micro finance', 'Micro Finance'), ('co-operative', 'Co-operative')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='availablefacility',
            name='operator_type',
            field=models.CharField(blank=True, choices=[('private', 'Private'), ('community', 'Community'), ('government', 'Government'), ('public', 'Public')], max_length=20, null=True),
        ),
    ]
