# Generated by Django 2.2.7 on 2019-11-21 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20191121_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availablefacility',
            name='bank_type',
            field=models.CharField(blank=True, choices=[('development', 'Development'), ('commercial', 'Commercial'), ('finance companies', 'Finance Companies'), ('micro finance', 'Micro Finance'), ('co-operative', 'Co-operative')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='availablefacility',
            name='education_type',
            field=models.CharField(blank=True, choices=[('school', 'School'), ('college', 'College'), ('kindergarten', 'Kinder Garten'), ('driving_school', 'Driving School'), ('library', 'Library')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='availablefacility',
            name='financial_type',
            field=models.CharField(blank=True, choices=[('bank', 'bank'), ('atm', 'atm'), ('bureau_de_change', 'bureau_de_change')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='availablefacility',
            name='health_type',
            field=models.CharField(blank=True, choices=[('hospital', 'Hospital'), ('veterinary', 'Veterinary'), ('clinic', 'Clinic'), ('dentist', 'Dentist'), ('pharmacy', 'Pharmacy'), ('health post', 'Health Post'), ('social facility', 'Social Facility'), ('doctors', 'Doctors')], max_length=30, null=True),
        ),
    ]
