# Generated by Django 2.2.7 on 2019-11-22 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20191121_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='service'),
        ),
        migrations.AlterField(
            model_name='suggesteduse',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='suggest'),
        ),
    ]
