# Generated by Django 2.2.7 on 2019-11-22 08:52

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20191122_0424'),
    ]

    operations = [
        migrations.AddField(
            model_name='province',
            name='boundary',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326),
        ),
    ]
