# Generated by Django 2.2.7 on 2019-11-25 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_province_boundary'),
    ]

    operations = [
        migrations.AddField(
            model_name='openspace',
            name='issue',
            field=models.TextField(blank=True, null=True),
        ),
    ]
