# Generated by Django 2.2.7 on 2019-11-26 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20191126_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openspace',
            name='access_to_site',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='openspace',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='openspace',
            name='catchment_area',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='openspace',
            name='ownership',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
