# Generated by Django 2.2.7 on 2019-11-26 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20191126_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openspace',
            name='title',
            field=models.TextField(),
        ),
    ]
