# Generated by Django 2.2.7 on 2019-11-26 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20191126_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='suggesteduse',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
