# Generated by Django 2.2.7 on 2019-11-27 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20191127_0601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='location',
        ),
    ]
