# Generated by Django 2.2.7 on 2019-11-27 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_remove_report_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='maps',
        ),
        migrations.AddField(
            model_name='gallery',
            name='type',
            field=models.CharField(blank=True, choices=[('map', 'Map'), ('image', 'Image')], max_length=15, null=True),
        ),
    ]
