# Generated by Django 2.2.7 on 2019-11-28 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_auto_20191127_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='availablefacility',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='facility'),
        ),
    ]
