# Generated by Django 2.2.7 on 2019-12-02 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_auto_20191129_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availablefacility',
            name='name',
            field=models.CharField(max_length=1000),
        ),
    ]
