# Generated by Django 2.2.7 on 2019-12-04 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_auto_20191204_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggesteduselist',
            name='name',
            field=models.CharField(max_length=1000),
        ),
    ]
