# Generated by Django 2.2.7 on 2019-12-05 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_auto_20191204_1026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suggestedusedata',
            old_name='suggested_use',
            new_name='suggested',
        ),
    ]
