# Generated by Django 2.2.7 on 2019-12-05 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_auto_20191205_0738'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suggestedusedata',
            old_name='suggested',
            new_name='suggested_use',
        ),
    ]
