# Generated by Django 2.2.7 on 2019-12-05 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_auto_20191205_0743'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('open_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='core.OpenSpace')),
            ],
        ),
        migrations.CreateModel(
            name='ServicesList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('icon', models.FileField(blank=True, null=True, upload_to='service')),
            ],
        ),
        migrations.DeleteModel(
            name='Services',
        ),
        migrations.AddField(
            model_name='servicedata',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='core.ServicesList'),
        ),
    ]
