# Generated by Django 2.2.7 on 2019-12-05 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_auto_20191205_1120'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServicesList',
            new_name='ServiceList',
        ),
    ]
