# Generated by Django 2.2.7 on 2019-12-10 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_auto_20191210_0528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openspace',
            name='access_to_site',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='openspace',
            name='capacity',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='openspace',
            name='elevation',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='openspace',
            name='total_area',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='openspace',
            name='usable_area',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='openspace',
            name='ward',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
