# Generated by Django 2.2.7 on 2019-12-10 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_auto_20191210_0535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openspace',
            name='capacity',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='openspace',
            name='total_area',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True),
        ),
    ]
