# Generated by Django 2.2.7 on 2019-12-11 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_auto_20191210_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openspace',
            name='capacity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='openspace',
            name='total_area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
