# Generated by Django 2.2.7 on 2019-12-11 11:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_auto_20191211_1013'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='createopenspace',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='openspace',
            name='capacity',
            field=models.FloatField(blank=True, default=Decimal('0.0000'), null=True),
        ),
        migrations.AlterField(
            model_name='openspace',
            name='total_area',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
