# Generated by Django 2.2.7 on 2019-12-12 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_auto_20191212_0552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
