# Generated by Django 2.2.7 on 2019-12-13 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_auto_20191213_0444'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='thumbnail',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='thumbs'),
        ),
    ]
