# Generated by Django 2.2.7 on 2019-12-16 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_auto_20191216_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availablefacility',
            name='type',
            field=models.CharField(blank=True, choices=[('health facility', 'Health Facility'), ('education facility', 'Education Facility'), ('security force', 'Security Force'), ('place of worship', 'Place Of Worship'), ('financial institution', 'Financial Institution'), ('helipad', 'Helipad')], max_length=30, null=True),
        ),
    ]
