# Generated by Django 2.2.7 on 2019-12-18 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_gallery_gallery_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='openspace',
            name='thumb_update',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='openspace',
            name='thumbnail',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='thumbs'),
        ),
    ]
