# Generated by Django 2.2.7 on 2020-01-10 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_auto_20200103_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='createopenspace',
            name='title_nep',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
