# Generated by Django 2.2.7 on 2020-01-19 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_createopenspace_title_nep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availablefacility',
            name='type',
            field=models.CharField(blank=True, choices=[('health facility', 'Health Facility'), ('education facility', 'Education Facility'), ('security force', 'Security Force'), ('place of worship', 'Place Of Worship'), ('financial institution', 'Financial Institution'), ('helipad', 'Helipad'), ('fire', 'Fire')], max_length=30, null=True),
        ),
    ]
