# Generated by Django 2.2.6 on 2020-02-12 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_auto_20200210_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openspace',
            name='total_area',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='openspace',
            name='usable_area',
            field=models.CharField(blank=True, default=0, max_length=1000, null=True),
        ),
    ]
