# Generated by Django 2.2.6 on 2020-02-13 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_auto_20200212_0547'),
    ]

    operations = [
        migrations.RenameField(
            model_name='openspace',
            old_name='thumb_update',
            new_name='geoserver_url',
        ),
        migrations.AddField(
            model_name='servicedata',
            name='is_available',
            field=models.CharField(blank=True, choices=[('yes', 'YES'), ('no', 'NO')], default='no', max_length=15, null=True),
        ),
    ]
