# Generated by Django 2.2.6 on 2020-02-13 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_auto_20200213_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openspace',
            name='geoserver_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
