# Generated by Django 2.2.6 on 2020-03-12 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_auto_20200214_0502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availablefacility',
            name='education_type',
            field=models.CharField(blank=True, choices=[('school', 'School'), ('college', 'College'), ('kindergarten', 'Kinder Garten'), ('higher_secondary', 'Higher Secondary'), ('lower_secondary', 'Lower Secondary'), ('driving_school', 'Driving School'), ('primary', 'Primary'), ('secondary', 'Secondary'), ('library', 'Library')], max_length=30, null=True),
        ),
    ]
