# Generated by Django 2.2.6 on 2020-03-12 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_auto_20200312_0558'),
    ]

    operations = [
        migrations.AddField(
            model_name='availablesubtype',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='available_sub_type', to='core.AvailableType'),
        ),
    ]
