# Generated by Django 2.2.6 on 2020-03-16 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_availablesubtype_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availablefacility',
            name='education_type',
        ),
        migrations.RemoveField(
            model_name='availablefacility',
            name='financial_type',
        ),
        migrations.RemoveField(
            model_name='availablefacility',
            name='health_type',
        ),
        migrations.RemoveField(
            model_name='availablefacility',
            name='type',
        ),
    ]
