# Generated by Django 2.2.6 on 2020-03-23 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_auto_20200322_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
