# Generated by Django 2.2.6 on 2020-03-24 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_report_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
