# Generated by Django 2.2.6 on 2020-03-24 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_auto_20200324_0336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='video',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
