# Generated by Django 2.2.6 on 2020-04-05 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_createopenspacepoints'),
    ]

    operations = [
        migrations.AddField(
            model_name='availablefacility',
            name='ward_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
