# Generated by Django 2.2.6 on 2020-04-06 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_availablefacility_ward_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='MunicipalityAvailableType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_source', models.CharField(max_length=300)),
                ('change_remarks', models.TextField(blank=True, null=True)),
                ('available_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.AvailableType')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Municipality')),
            ],
        ),
    ]
