# Generated by Django 2.2.6 on 2020-04-06 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_municipalityavailabletype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipalityavailabletype',
            name='data_source',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
