# Generated by Django 2.2.6 on 2020-04-06 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0082_auto_20200406_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='availablefacility',
            name='op_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
