# Generated by Django 2.2.6 on 2020-04-07 10:36

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0084_auto_20200407_0636'),
    ]

    operations = [
        migrations.AddField(
            model_name='openspace',
            name='area_change',
            field=models.FloatField(default=Decimal('0.0000')),
        ),
        migrations.AddField(
            model_name='openspace',
            name='change_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='openspace',
            name='coordinates_elevation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='openspace',
            name='educational_infrastructures',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='openspace',
            name='health_facilities',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='openspace',
            name='helipad',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='openspace',
            name='market',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='openspace',
            name='oid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='openspace',
            name='perimeter',
            field=models.FloatField(default=Decimal('0.0000')),
        ),
        migrations.AddField(
            model_name='openspace',
            name='security',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='openspace',
            name='usable_2013',
            field=models.FloatField(default=Decimal('0.0000')),
        ),
    ]
