# Generated by Django 2.2.6 on 2020-04-07 11:54

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0085_auto_20200407_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openspace',
            name='area_change',
            field=models.FloatField(blank=True, default=Decimal('0.0000'), null=True),
        ),
        migrations.AlterField(
            model_name='openspace',
            name='perimeter',
            field=models.FloatField(blank=True, default=Decimal('0.0000'), null=True),
        ),
        migrations.AlterField(
            model_name='openspace',
            name='usable_2013',
            field=models.FloatField(blank=True, default=Decimal('0.0000'), null=True),
        ),
    ]
