# Generated by Django 2.2.6 on 2020-04-08 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0086_auto_20200407_1154'),
    ]

    operations = [
        migrations.CreateModel(
            name='MunicipalityQuestionsData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_source', models.CharField(blank=True, max_length=300, null=True)),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Municipality')),
            ],
        ),
        migrations.AddField(
            model_name='questionsdata',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_data', to='core.MunicipalityQuestionsData'),
        ),
    ]
