# Generated by Django 2.2.6 on 2020-04-08 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0087_auto_20200408_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionsdata',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_data', to='core.MunicipalityQuestionsData'),
        ),
    ]
