# Generated by Django 2.2.6 on 2020-04-15 06:03

from decimal import Decimal
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0088_auto_20200408_0918'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainCommunitySpace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_community_spaces', to='core.Municipality')),
            ],
        ),
        migrations.CreateModel(
            name='CommunitySpace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ward', models.CharField(blank=True, max_length=100, null=True)),
                ('cid', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(max_length=1000)),
                ('description', models.TextField(blank=True, null=True)),
                ('current_land_use', models.CharField(blank=True, max_length=300, null=True)),
                ('coordinates_elevation', models.CharField(blank=True, max_length=200, null=True)),
                ('usable_area', models.FloatField(blank=True, default=Decimal('0.0000'), null=True)),
                ('total_area', models.FloatField(blank=True, default=Decimal('0.0000'), null=True)),
                ('elevation', models.CharField(blank=True, max_length=1000, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('capacity', models.FloatField(blank=True, default=Decimal('0.0000'), null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_spaces', to='core.District')),
                ('main_community_space', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='community_spaces', to='core.MainCommunitySpace')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_spaces', to='core.Municipality')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_spaces', to='core.Province')),
            ],
        ),
    ]
