# Generated by Django 2.2.6 on 2020-04-15 06:15

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0089_communityspace_maincommunityspace'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityspace',
            name='polygons',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326),
        ),
    ]
