# Generated by Django 2.2.7 on 2019-11-20 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0006_auto_20191119_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='location',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
