# Generated by Django 2.2.7 on 2020-01-10 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0008_auto_20191122_0424'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='description_nep',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='email_nep',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='location_nep',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='num1_nep',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='num2_nep',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='title_nep',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='openspaceapp',
            name='description_nep',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='openspaceapp',
            name='title_nep',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='num1',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='num2',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='openspaceapp',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
