# Generated by Django 2.2.6 on 2020-03-23 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0010_aboutheader_criteriadescription_criteriatype_openspacecriteria'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhyMapOpenIcon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.FileField(upload_to='icon')),
                ('description', models.TextField(blank=True, null=True)),
                ('description_nep', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WhyMapOpenSpace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('title_nep', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('description_nep', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='criteriadescription',
            name='description_nep',
            field=models.TextField(blank=True, null=True),
        ),
    ]
