# Generated by Django 2.2.6 on 2020-04-01 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0013_auto_20200401_0316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutheader',
            name='url',
        ),
        migrations.AddField(
            model_name='aboutheader',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='front'),
        ),
    ]
