# Generated by Django 2.2.6 on 2019-11-05 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('title_nep', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('description_nep', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OpenSpaceDef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('title_nep', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('description_nep', models.TextField(blank=True, null=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='open_space_def')),
            ],
        ),
        migrations.CreateModel(
            name='OpenSpaceIde',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('title_nep', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('description_nep', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
