# Generated by Django 2.2.6 on 2019-11-06 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openspacedef',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
