# Generated by Django 2.2.6 on 2019-11-06 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0002_auto_20191106_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openspacedef',
            name='video',
            field=models.TextField(blank=True, null=True),
        ),
    ]
