# Generated by Django 2.2.6 on 2019-11-01 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191025_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Replied')], default=0),
        ),
    ]
