# Generated by Django 2.2.6 on 2019-11-01 05:25

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20191101_0418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openspace',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='openspace',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='report',
            name='description',
        ),
        migrations.AddField(
            model_name='openspace',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='space'),
        ),
        migrations.AddField(
            model_name='openspace',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='openspace',
            name='maps',
            field=models.ImageField(blank=True, null=True, upload_to='maps'),
        ),
        migrations.AddField(
            model_name='report',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='space'),
        ),
        migrations.AddField(
            model_name='report',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
    ]
