# Generated by Django 2.2.6 on 2019-11-01 11:19

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20191101_0525'),
    ]

    operations = [
        migrations.AddField(
            model_name='openspace',
            name='catchment_area',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='openspace',
            name='current_land_use',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='openspace',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='openspace',
            name='ownership',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='openspace',
            name='space',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ward_num', models.IntegerField()),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ward', to='core.Municipality')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('ans', models.BooleanField(default=True)),
                ('open_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.OpenSpace')),
            ],
        ),
        migrations.AddField(
            model_name='openspace',
            name='ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='open_space', to='core.Ward'),
        ),
    ]
