# Generated by Django 2.2.6 on 2019-11-04 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20191101_1119'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateOpenSpace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='identify_open_space')),
            ],
        ),
        migrations.RenameField(
            model_name='openspace',
            old_name='space',
            new_name='polygon',
        ),
        migrations.AddField(
            model_name='openspace',
            name='access_to_site',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='openspace',
            name='elevation',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='openspace',
            name='special_feature',
            field=models.TextField(blank=True, null=True),
        ),
    ]
