# Generated by Django 2.2.6 on 2019-11-05 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_educationfacility_healthfacility_nearbyamenities'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('audio', models.FileField(blank=True, null=True, upload_to='audio')),
                ('video', models.FileField(blank=True, null=True, upload_to='video')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('publication', models.FileField(blank=True, null=True, upload_to='publication')),
                ('category', models.IntegerField(choices=[(0, 'Plans and Policies'), (1, 'Research'), (2, 'Multimedia')], default=0)),
                ('document_type', models.IntegerField(choices=[(0, 'publication'), (1, 'audio'), (2, 'video')], default=0)),
            ],
        ),
    ]
