# Generated by Django 2.2.6 on 2019-11-07 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20191107_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='province',
            name='code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
