# Generated by Django 2.2.6 on 2019-11-11 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20191111_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openspace',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='district', to='core.District'),
        ),
        migrations.AlterField(
            model_name='openspace',
            name='municipality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='municipality', to='core.Municipality'),
        ),
        migrations.AlterField(
            model_name='openspace',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='province', to='core.Province'),
        ),
    ]
