# Generated by Django 2.2.6 on 2020-01-20 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_auto_20200103_1110'),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='District',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='District', to='core.District'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Municipality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Municipality', to='core.Municipality'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Province', to='core.Province'),
        ),
    ]
