# Generated by Django 2.2.6 on 2020-01-22 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20200120_1049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='District',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='Province',
        ),
    ]
