# Generated by Django 2.2.6 on 2020-01-22 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20200122_1121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='Municipality',
            new_name='municipality',
        ),
    ]
