# Generated by Django 2.2.6 on 2020-03-17 04:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0074_auto_20200316_0453'),
        ('dashboard', '0004_auto_20200122_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAgency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_name', models.CharField(blank=True, max_length=300, null=True)),
                ('address', models.CharField(blank=True, max_length=300, null=True)),
                ('contact', models.CharField(blank=True, max_length=300, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AgencyMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.UserAgency')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_agency', to='core.Municipality')),
                ('open_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_agency', to='core.OpenSpace')),
            ],
        ),
    ]
