# Generated by Django 2.2.6 on 2020-03-17 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_agencymessage_useragency'),
    ]

    operations = [
        migrations.AddField(
            model_name='useragency',
            name='email',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
