# Generated by Django 2.2.6 on 2020-03-23 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20200322_0628'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencymessage',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
